//! Extract every ```rust block from the consumer-facing docs into a Rust source
//! file the crate compiles under `cfg(test)`.
//!
//! The README's examples are fragments: they assume an ambient `runtime`, a
//! `spec`, a `job`, and application-side types (`Doc`, `MyError`, `load()`).
//! Each block is therefore wrapped in one async scaffold function whose
//! parameters and prelude supply those names (see `src/lib.rs::prelude`), and
//! compiled — never run. A fragment that names a facade item that no longer
//! exists, or calls it with the wrong shape, fails `cargo test --workspace`.
//!
//! Blocks are taken verbatim: nothing is rewritten, and no hidden `# ` lines are
//! required in the Markdown, so the docs stay readable on GitHub.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Docs whose ```rust blocks are consumer-facing promises.
const SOURCES: &[&str] = &["README.md", "docs/taskmesh-external-interface.md"];

struct Block {
    source: &'static str,
    index: usize,
    /// 1-based line of the opening fence in the source file.
    line: usize,
    code: String,
}

/// An open code fence while scanning: only `rust` fences collect lines, but
/// every fence is tracked so its closing ``` is not mistaken for an opening one.
struct OpenFence<'a> {
    /// 1-based line of the opening fence; `None` for a non-Rust fence.
    rust_at: Option<usize>,
    lines: Vec<&'a str>,
}

/// Fenced ```rust blocks, in document order. Only the exact `rust` info string
/// (optionally with attributes after a comma) is a compiled example; `text`,
/// `toml`, `sh` and unlabelled fences are not.
fn rust_blocks(source: &'static str, markdown: &str) -> Vec<Block> {
    let mut blocks = Vec::new();
    let mut open: Option<OpenFence<'_>> = None;
    for (offset, line) in markdown.lines().enumerate() {
        match open.as_mut() {
            None => {
                if let Some(info) = line.strip_prefix("```") {
                    let info = info.trim();
                    let is_rust = info == "rust" || info.starts_with("rust,");
                    open = Some(OpenFence {
                        rust_at: is_rust.then_some(offset + 1),
                        lines: Vec::new(),
                    });
                }
            }
            Some(fence) => {
                if line.trim_end() == "```" {
                    if let Some(line_no) = fence.rust_at {
                        blocks.push(Block {
                            source,
                            index: blocks.len(),
                            line: line_no,
                            code: format!("{}\n", fence.lines.join("\n")),
                        });
                    }
                    open = None;
                } else {
                    fence.lines.push(line);
                }
            }
        }
    }
    assert!(open.is_none(), "{source}: unterminated code fence");
    blocks
}

fn module_name(block: &Block) -> String {
    let stem = Path::new(block.source)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("doc")
        .replace(|c: char| !c.is_ascii_alphanumeric(), "_");
    format!("{}_block_{}", stem.to_ascii_lowercase(), block.index)
}

fn render(blocks: &[Block]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by tools/doc-examples/build.rs — do not edit.\n");
    out.push_str("pub const SOURCES: &[(&str, usize)] = &[\n");
    for source in SOURCES {
        let count = blocks.iter().filter(|b| b.source == *source).count();
        out.push_str(&format!("    ({source:?}, {count}),\n"));
    }
    out.push_str("];\n\n");
    for block in blocks {
        let name = module_name(block);
        out.push_str(&format!(
            "/// {}:{} — ```rust block #{}, verbatim.\n",
            block.source, block.line, block.index
        ));
        out.push_str("#[allow(unused, dead_code, unreachable_code, clippy::all, clippy::pedantic, clippy::nursery)]\n");
        out.push_str(&format!("pub mod {name} {{\n"));
        out.push_str("    use crate::prelude::*;\n\n");
        out.push_str(
            "    pub async fn block(\n        runtime: &TokioRuntime,\n        spec: TaskSpec,\n        job: fn() -> Result<Doc, ParseError>,\n    ) -> Result<(), Box<dyn std::error::Error>> {\n",
        );
        for line in block.code.lines() {
            // Indent non-empty lines only, so the generated file stays free of
            // trailing whitespace (rustfmt-clean if anyone ever looks at it).
            if !line.is_empty() {
                out.push_str("        ");
                out.push_str(line);
            }
            out.push('\n');
        }
        out.push_str("        Ok(())\n    }\n}\n\n");
    }
    out
}

fn main() -> Result<(), String> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo = manifest_dir
        .ancestors()
        .nth(2)
        .expect("tools/doc-examples sits two levels below the repository root");
    let mut blocks = Vec::new();
    for source in SOURCES {
        let path = repo.join(source);
        println!("cargo:rerun-if-changed={}", path.display());
        let markdown = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        blocks.extend(rust_blocks(source, &markdown));
    }
    assert!(
        !blocks.is_empty(),
        "no ```rust blocks found in {SOURCES:?}: the extraction is broken, not the docs"
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("blocks.rs"), render(&blocks))
        .map_err(|error| format!("cannot write blocks.rs: {error}"))?;
    Ok(())
}
