organization:
    id: ba92efc9-2125-4150-ac6c-10862db69910
    name: Song
project:
    id: 2ad35b62-9fed-4a19-9959-83ea8a98fb84
    slug: circleci/Q3G2VbitoZmaQSKihvptcF/6Hiohc4JcUhsyHHGRnRcro
    name: quanta-taskmesh
